# Generated by Django 5.1.1 on 2024-09-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazzat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='descriptionn',
        ),
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
